[game]
id = "my-game"
name = "My Game"
version = "0.1.0"

[server]
module = "server/dist/index.js"

[client]
module = "client/dist/index.js"

[content]
prototypes = ["content/prototypes"]
maps = ["maps"]
resources = ["resources"]
localization = ["localization"]
